config/routes.rb
Forum::Application.routes.draw do
  get "projects/home"

  get "users/login"

  resources :users

  root :to => 'users#login' , :as=>'login'

  match '/validate_login' => 'users#validate_login' , :as => 'validate_login'
  match '/validate_signup' => 'users#validate_signup' , :as => 'validate_signup'
  match '/signup' => 'users#signup' , :as => 'signup'
  match 'auth/google_oauth2/callback' => 'users#auth2callback'
end

app/models/user.rb
  
require 'digest/sha1'

class User < ActiveRecord::Base
  
    attr_protected :id, :salt
  validates_uniqueness_of :email_id
  validates_confirmation_of :password
  validates_format_of :email_id, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => "Invalid email"  
  validates_presence_of :email_id,:password,:first_name,:last_name,:password_confirmation
  attr_accessor :email_id,:password,:first_name,:last_name,:password_confirmation
  
  def before_save(user)
    
  end
  
 
  
  def self.random_string(len)
   chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
   newpass = ""
   1.upto(len) { |i| newpass << chars[rand(chars.size-1)] }
   return newpass
  end
  
  def password=(pass)
   self.salt = User.random_string(10) if !self.salt?
   self.password_hash = User.encrypt(pass, self.salt)
  end
  
  def self.encrypt(pass, salt)
   Digest::SHA1.hexdigest(pass+salt)
  end
  
  def self.authenticate(email_id, pass)
    u=find(:first, :conditions=>["email_id = ?", email_id])
    return nil if u.nil?
    return u if User.encrypt(pass, u.salt)==u.password_hash
    nil
  end  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def home
    
    
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def signup
    @user = User.new
  end

  def login
   @user = User.new
  end
  
  def validate_signup
    @user = User.new(@params[:user])
    if request.post?
      if user.save?
        session[:user] = User.authenticate(@user.email_id,@user.password)
        redirect_to :action=>'home'
       end
    end
  end
  
  def validate_login
    if request.post?
      if (session[:user]=User.authenticate(params[:user][:email_id],params[:user][:password]))
        puts "################ SESSION CREATED ",session[:user].to_yaml
        redirect_to :controller=>'todo_lists' , :action=>'home'
       return
      else
        flash[:message] = "Invalid username/password"
      end
    end
    redirect_to :action=>'login'
  end


  def logout
    session[:user] = nil
    flash[:message] = 'Logged out'
    redirect_to :action => 'login'
  end

 def auth2callback
   auth_param = request.env["omniauth.auth"]
   if (session[:user]= auth_param.extra.raw_info.email)
    redirect_to  :action=>'home'
    else
        flash[:message] = "Invalid username/password"
    redirect_to :action=>'login'
   end
 end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/home.html.erb
<h1>Projects#home</h1>
<p>Find me in app/views/projects/home.html.erb</p>

app/views/users/login.html.erb
 <div class="container">
 	
	<legend>Login</legend>
	
	 
	<div class="well">
   
<div id="page-wrap">
	<div id="error"><%=flash[:message]%></div>
   <%= form_for (@user),:url => {:action =>:validate_login, :method => "post" },:html=>{:class=>'form-signin'} do |f|%>  
      	 <div class="text-wrap"><%= f.text_field :email_id ,:id => 'input-box',:placeholder=>"Email"%></div>
   	 <div class="text-wrap"><%=f.password_field :password ,:id => 'input-box',:placeholder=>"Password"%></div>
   	 <div class="text-wrap"><%= f.submit "Login" , :id=>'btn-submit',:class=>'btn btn-large btn-primary'%></div>
    <% end %>
    
    <div id="links">
       <%= link_to "Login with google","/auth/google_oauth2" %>
       <%= link_to "Signup","/signup" %>
    </div>
</div>


</div>
</div>

app/views/users/signup.html.erb
 <div class="container">
	<legend>Sign Up</legend>
	<div class="well">
		<%= form_for (@user),:url => {:action =>:validate_signup, :method => "post" },:html=>{:class=>'form-horizontal',:id=>'signup'} do |f|%>  
	        <div class="control-group">
	            <label class="control-label">First Name</label>
	            <div class="controls">
	                <div class="input-prepend">
	                	<%= f.text_field :first_name ,:id => 'fname',:placeholder=>"First Name",:class=>'input-xlarge'%>
	                </div>
	            </div>	        </div>
	        <div class="control-group ">
	            <label class="control-label">Last Name</label>
	            <div class="controls">
	                <div class="input-prepend">
	                	<%= f.text_field :last_name ,:id => 'lname',:placeholder=>"Last Name",:class=>'input-xlarge'%>
	                </div>
	            </div>
	        </div>
	        <div class="control-group">
	            <label class="control-label">Email</label>
	            <div class="controls">
	                <div class="input-prepend">
	                	<%= f.text_field :email_id ,:id => 'email',:placeholder=>"Email",:class=>'input-xlarge'%>
	                </div>
	            </div>
	        </div>
	        <div class="control-group">
	            <label class="control-label">Gender</label>
	            <div class="controls">
	 
	                    <p><div id="gender" name="gender" class="btn-group" data-toggle="buttons-radio">
	                    <button type="button" class="btn btn-info">Male</button>
	                    <button type="button" class="btn btn-info">Female</button>
	 
	                  </div></p>
	            </div>
	        </div>
	        <div class="control-group">
	            <label class="control-label">Password</label>
	            <div class="controls">
	                <div class="input-prepend">
	                	<%= f.password_field :password ,:id => 'passwd',:placeholder=>"Password",:class=>'input-xlarge'%>
	                </div>
	            </div>
	        </div>
	        <div class="control-group">
	            <label class="control-label">Confirm Password</label>
	            <div class="controls">
	                <div class="input-prepend">
	                	<%= f.password_field :password_confirmation ,:id => 'conpasswd',:placeholder=>"Re-enter Password",:class=>'input-xlarge'%>
	                </div>
	            </div>
	        </div>
	 
	        <div class="control-group">
	        <label class="control-label"></label>
	          <div class="controls">
	           <button type="submit" class="btn btn-success" >Create My Account</button>
	          	 <%= link_to "<<Back",login_url %>
	          </div>
	    </div>
	 
	     <%end%>
	 
	   </div>